blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<pk>', BlogDetailView.as_view(), name='detail'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('view/<pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),

]

curse_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

blog/models.py
from django.conf import settings
from django.db import models
from pytils.translit import slugify

from main.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    slug = models.CharField(max_length=150, unique=True, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое')
    preview_img = models.ImageField(upload_to='blog/images/', verbose_name='Превью', **NULLABLE)
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content',)
    success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview_img')
    success_url = reverse_lazy('blog:list')


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        post.views_count += 1
        post.save()
        return super().get(request, *args, **kwargs)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)

blog/templates/blog/blog_confirm_delete.html
{% extends "main/base.html" %}
{% block title %} Удаление блога {{ object.title }} {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <form method="post">
                            <p>Вы точно хотите удалить Блог '{{ object.title }}'? </p>
                            <button type="submit" class="btn btn-danger">
                                Подтвердить
                            </button>

                            <a class="p-2 btn btn-outline-primary" href="/blog/">Отменить</a>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "main/base.html" %}
{% block title %} Блог {{ object.title }} {% endblock %}
{% block content %}
<div class="container">
    <h1>{{ object.title }}</h1>
    <p>Дата создания : {{ object.date_of_creation }}</p>
    <p>Описание : {{ object.content }}</p>
    <p>Просмотры : {{ object.views_count }}</p>

<a class="p-2 btn btn-lg btn-primary" href="/blog">Назад</a>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "main/base.html" %}
{% block title %} Блог {{ object.title }} {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}</button>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends "main/base.html" %}
{% block title %} Блог {% endblock %}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="row justify-content-center mb-5">
      <div class="col-md-12">
        <a class="btn btn-primary btn-block" href="{% url 'blog:create' %}">Добавить запись</a>
      </div>
    </div>
    <h1>Список блоговых записей</h1>

    <div class="row">
      {% for post in posts %}
      <div class="col-md-12 mb-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><a href="{% url 'blog:view' post.pk %}">{{ post.title }}</a></h2>
            <p class="card-text">{{ post.content }}</p>
            <a href="{% url 'blog:detail' post.slug %}">
              <img alt="Превью" class="img-fluid" src="{% mediafile post.preview_img %}" />
            </a>
            <p class="card-text">Просмотры: {{ post.views_count }}</p>
            <div class="btn-group" role="group">
              <a href="{% url 'blog:view' post.pk %}" class="btn btn-primary">Подробнее</a>
              <a href="{% url 'blog:update' post.pk %}" class="btn btn-success">Редактировать</a>
              <a href="{% url 'blog:delete' post.pk %}" class="btn btn-danger">Удалить</a>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-md-12 text-center">
        <p>Пока нет ни одной записи.</p>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}