blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<pk>', BlogDetailView.as_view(), name='detail'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('view/<pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),

]

curse_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, PasswordRecoveryView, verification_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('verification/', verification_view, name='verification'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=50, **NULLABLE, verbose_name='Номер телефона')
    country = models.CharField(max_length=50, verbose_name='Страна')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='Аватар')
    is_verified_email = models.BooleanField(default=False)
    verification_code = models.CharField(max_length=6, **NULLABLE, verbose_name='Код верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'email', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class PasswordRecoveryForm(forms.Form):
    email = forms.EmailField(label='Email')


class VerificationCodeForm(forms.Form):
    verification_code = forms.CharField(max_length=6, label='Код верификации')

users/views.py
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
import random
import string
from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.views.generic import CreateView, UpdateView, FormView
from users.forms import UserRegisterForm, UserProfileForm, PasswordRecoveryForm, VerificationCodeForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    context_object_name = 'users'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        verification_code = ''.join(random.choice(string.digits) for _ in range(6))
        subject = 'Код верификации'
        message = f'Ваш код верификации: {verification_code}'
        recipient_email = form.cleaned_data['email']
        send_mail(
            subject=subject,
            message=message,
            recipient_list=[recipient_email],
            from_email=settings.EMAIL_HOST_USER,
            fail_silently=False,

        )
        user = form.save(commit=False)
        user.verification_code = verification_code
        user.save()

        return redirect('users:verification')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/user_form.html'

    def get_object(self, queryset=None):
        return self.request.user


class PasswordRecoveryView(FormView):
    form_class = PasswordRecoveryForm
    template_name = 'users/password_recovery.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = User.objects.get(email=email)
        length = 16
        alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
        password = get_random_string(length, alphabet)
        user.set_password(password)
        user.save()
        subject = 'Восстановление пароля'
        message = f'Ваш новый пароль: {password}'
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


def verification_view(request):
    if request.method == 'POST':
        form = VerificationCodeForm(request.POST)
        if form.is_valid():
            entered_code = form.cleaned_data['verification_code']
            try:
                user = User.objects.get(verification_code=entered_code)
                if user:
                    user.is_verified_email = True
                    user.save()
                    return redirect('main:home')
            except User.DoesNotExist:
                form.add_error('verification_code', 'Пользователь с таким кодом верификации не найден')
    else:

        form = VerificationCodeForm()

    return render(request, 'users/verification.html', {'form': form})

users/templates/users/login.html
{% extends "main/base.html" %}
{% block title %} Логин {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">
                                Вход
                            </button>
                            <a class="p-2 btn btn-danger" href="{% url 'users:register' %}">Регистрация</a>
                            <a href="{% url 'users:password_recovery' %}" class="btn btn-secondary">Восстановить
                                пароль</a>

                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

users/templates/users/password_recovery.html
{% extends 'main/base.html' %}
{% block title %} Восстановление пароля {% endblock %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-12">
                <h1>Восстановление пароля</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Восстановить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "main/base.html" %}
{% block title %} Регистрация {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-body">
                        <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends "main/base.html" %}
{% block title %} Профиль {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-4">
          <div class="card">
            <div class="card-header">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">
                               Сохранить </button>
                        <a class="p-1 btn btn-lg btn-primary" href="/">Назад</a>
                          <a class="p-2 btn btn-danger" href="{% url 'users:logout' %}">Выйти из аккаунта</a>
                        </div>
                        </div>
                        </form>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/verification.html
{% extends 'main/base.html' %}
{% block title %} Верификация {% endblock %}
{% block content %}


<body>
<div class="row justify-content-center">
     <div class="col-4">
          <div class="card">
    <h1>Введите код верификации</h1>

        <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-success">Подтвердить</button>

{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors.verification_code }}
    </div>
{% endif %}
    </form>
</div>
         </div>
    </div>
</body>
</html>
{% endblock %}