blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<pk>', BlogDetailView.as_view(), name='detail'),
    path('update/<pk>', BlogUpdateView.as_view(), name='update'),
    path('view/<pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<pk>', BlogDeleteView.as_view(), name='delete'),

]

curse_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    ClientCreateView, ClientUpdateView, ClientListView, ClientDeleteView,
    MailingCreateView, MailingUpdateView, MailingListView, MailingDeleteView, MailingDetailView,
    MessageCreateView, HomeView, ReportView,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create'),
    path('mailing/<pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing/delete/<pk>', MailingDeleteView.as_view(), name='delete'),
    path('mailing/update/<pk>', MailingUpdateView.as_view(), name='update'),
    path('mailing/create_message/<mailing_pk>', MessageCreateView.as_view(), name='create_message'),
    path('client/update/<pk>', ClientUpdateView.as_view(), name='client_update'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('report/',  cache_page(60)(ReportView.as_view()), name='report'),

    ]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, PasswordRecoveryView, verification_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('verification/', verification_view, name='verification'),

]

main/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=150, verbose_name='Имя')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активный')

    def __str__(self):
        return self.full_name


class Mailing(models.Model):
    FREQUENCY_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    ]
    STATUS_CHOICES = [
        ('created', 'Created'),
        ('running', 'Running'),
        ('completed', 'Completed'),
    ]
    time_to_send = models.DateTimeField()
    end_time = models.DateTimeField(**NULLABLE)
    frequency = models.CharField(max_length=20, choices=FREQUENCY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    recipients = models.ManyToManyField(Client)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)


class Message(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)


class MailingLog(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    attempt_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20)
    response = models.TextField(blank=True)

main/forms.py
from django import forms
from .models import Client, Mailing, Message


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment', 'is_active']


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['time_to_send', 'end_time', 'frequency', 'status', 'recipients']
        widgets = {
            'recipients': forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['recipients'].queryset = user.client_set.all()


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']

main/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from blog.models import Blog
from .models import Client, Mailing, Message, MailingLog
from .forms import ClientForm, MailingForm, MessageForm


class HomeView(TemplateView):
    template_name = 'main/home.html'
    extra_context = {
        'title': 'Главная страница',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_mailings_count = Mailing.objects.filter(status__in=['created', 'started']).count()
        context['active_mailings_count'] = active_mailings_count
        unique_clients_count = Client.objects.filter(is_active=True).distinct().count()
        context['unique_clients_count'] = unique_clients_count
        all_posts = list(Blog.objects.all())
        context['random_blog_posts'] = sample(all_posts, min(3, len(all_posts)))
        context['object_list'] = Mailing.objects.all()
        user = self.request.user
        user_group_names = [group.name for group in user.groups.all()]
        context['user_group_names'] = user_group_names
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'main/client_form.html'
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'main/client_form.html'
    success_url = reverse_lazy('main:client_list')


class ClientListView(ListView):
    model = Client
    template_name = 'main/client_list.html'
    context_object_name = 'clients'


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'main/create_mailing.html'
    success_url = reverse_lazy('main:mailing')

    def form_valid(self, form):
        new_mailing = form.save()
        new_mailing.owner = self.request.user
        new_mailing.save()
        self.mailing_pk = new_mailing.pk
        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'main/mailing_detail.html'
    context_object_name = 'mailing'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = Message.objects.filter(mailing=self.object)
        return context


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing')

    def form_valid(self, form):
        if form.is_valid():
            new_mailing = form.save()
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)


class MailingListView(ListView):
    model = Mailing
    template_name = 'main/mailing_list.html'
    context_object_name = 'mailings'


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mailing')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'main/create_message.html'
    success_url = reverse_lazy('main:mailing')
    context_object_name = 'messages'

    def form_valid(self, form):
        mailing_pk = self.kwargs['mailing_pk']
        mailing = get_object_or_404(Mailing, pk=mailing_pk)
        message = form.save(commit=False)
        message.mailing = mailing
        message.owner = self.request.user
        message.save()

        return redirect('main:mailing_detail', pk=mailing_pk)


class ReportView(ListView):
    model = MailingLog
    template_name = 'main/report.html'
    context_object_name = 'logs'

    def get_queryset(self):
        return MailingLog.objects.filter(status='success')

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a href="{% url 'main:home' %}">

    </a>

    <div class="col-7">
    <a class="p-2 btn btn-outline-primary " href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'main:client_list' %}">Клиенты</a>

        <a class="p-2 btn btn-outline-primary " href="/mailing/">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
       <a class="p-2 btn btn-outline-primary" href="{% url 'main:report' %}">Логи</a>

    </div>



    <div class="col-4"></div>
{% if user.is_authenticated %}
  <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}"> {{ user.email }} </a>
{% else %}
  <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
{% endif %}


    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылочка</h1>
    <p class="lead">Рассылочка - сервис для создания рассылок и ведения блога</p>
</div>
{% block content %}

{% endblock %}
<div class='container'>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Рассылочка
                <small class="d-block mb-3 text-black">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-black" href="/">Рассылки</a></li>
                    <li><a class="text-black" href="{% url 'blog:list' %}">Блог</a></li>
                    <li><a class="text-black" href="/">Контакты</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-black" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-black" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>

    </footer>
</div>


<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends "main/base.html" %}
{% block title %} Удаление клиента {{ object.title }} {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <form method="post">
                            <p>Вы точно хотите удалить клиента '{{ client.full_name }}'? </p>
                            <button type="submit" class="btn btn-danger ">
                                Подтвердить
                            </button>

                            <a class="p-2 btn btn-outline-primary" href="/mailing/">Отменить</a>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}

    <form method="post" enctype="multipart/form-data">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <h1>Добавление Клиента</h1>
                <div class="col-md-6">
                <div class="card">
                    <div class="card-body">

                            {% csrf_token %}

                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
         </div>
    </form>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<div class="container">
    <div class="row justify-content-center mb-5">
        <div class="col-md-12">
    {% if user.is_authenticated %}

            <h2>Список клиентов</h2>
            <a class="btn btn-primary" href="{% url 'main:client_create' %}">Добавить клиента</a>
            <hr>
        </div>
    {% endif %}
    <ul>

        {% for client in clients %}
            {{ client.full_name }} ({{ client.email }})
        {% if user.is_authenticated %}
        <a class="btn btn-danger" href="{% url 'main:client_delete' client.pk %}">Удалить</a>
                    <a class="btn btn-success" href="{% url 'main:client_update' client.pk %}">Редактировать</a>

        <hr>
        {% endif %}
         {% empty %}
      <li class="list-group-item text-center">Пока нет ни одного клиента.</li>
        {% endfor %}
    </ul>

</div>
    </div>
            </div>
{% endblock %}

main/templates/main/create_mailing.html
{% extends 'main/base.html' %}

{% block content %}


<form method="post">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-12">
                    <h2>создание рассылки</h2>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Создать рассылку</button>
                </div>
            </div>
        </div>
    </div>

</form>
{% endblock %}

main/templates/main/create_message.html
{% extends 'main/base.html' %}

{% block content %}


<form method="post">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-12">
                    <h2>создание сообщения</h2>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Создать сообщение</button>
                </div>
            </div>
        </div>
    </div>

</form>
{% endblock %}

main/templates/main/delete_mailing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %} Домашняя страница {% endblock %}
{% block content %}
<div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1>Сейчас вы на главной странице </h1>
        <figure class="p-3 mb-0">

            Количество клиентов : {{ unique_clients_count }}<br>
            Количество активных рассылок: {{ active_mailings_count }}<br>

        </figure>

        <h1>Вы можете выбрать один из пунктов меню</h1>
        <a href="{% url 'main:mailing' %}"><h2>Вы можете посмотреть список рассылок.</h2></a>
        <a href="{% url 'main:client_list' %}"><h2>Вы можете посмотреть список наших клиентов.</h2></a>
        <a href="{% url 'blog:list' %}"><h2>Вы можете просмотреть записи в блоге или создать их.</h2></a>
        {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}"><h2>Вы можете выйти из своего аккаунта.</h2></a>
        {% else %}
        <a href="{% url 'users:login' %}"><h2>
            Вы можете авторизироваться или зарегистрироваться у нас на сайте.</h2></a>
        {% endif %}
    </div>


</div>
{% for item in random_blog_posts %}
<div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2>случайная запись из блога номер {{ item.pk }}</h2>
        <h2><a href="/">{{ item.title }}</a></h2>
        <p>{{ post.content }}</p>
        <p>Просмотры: {{ post.views_count }}</p>
        <a href="{% url 'blog:view' item.pk %}" class="btn btn-primary">Подробнее</a>

        <hr>
        {% empty %}
         <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3>Пока нет ни одной записи блога.</h3>
             </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends "main/base.html" %}
{% block title %} Удаление рассылки {{ object.title }} {% endblock %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <form method="post">
                            <p>Вы точно хотите удалить рассылку '{{ mailing.name }}'? </p>
                            <button type="submit" class="btn btn-danger ">
                                Подтвердить
                            </button>

                            <a class="p-2 btn btn-outline-primary" href="/mailing/">Отменить</a>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container mt-5">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="row justify-content-center mb-5">
      <div class="col-md-12">
        <h2>Детали рассылки</h2>
        <p>Номер рассылки: {{ mailing.id }}</p>
        <p>Время старта: {{ mailing.time_to_send }}</p>
        <p>Время конца: {{ mailing.end_time }}</p>
        <h3>Сообщения в рассылке:</h3>
        <ul class="list-group">
          {% for message in messages %}
          <li class="list-group-item">
              <p>Тема : {{ message.body }}</p>
            <p>Сообщение : {{ message.subject }}</p>
          </li>
          {% endfor %}
        </ul>
        <div class="mt-3">
          <a class="btn btn-danger" href="{% url 'main:delete' mailing.pk %}">Удалить</a>
          <a class="btn btn-outline-primary" href="{% url 'main:update' mailing.pk %}">Редактировать</a>
          <a class="btn btn-primary" href="{% url 'main:mailing' %}">К рассылкам</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends "main/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends "main/base.html" %}
{% block title %} Список рассылок {% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="row justify-content-center mb-5">
      <div class="col-md-12">
        {% if user.is_authenticated %}
        <h2>Список рассылок</h2>
        <a class="btn btn-success btn-block" href="{% url 'main:create' %}">Добавить запись</a>
        {% endif %}
      </div>
    </div>

    <ul class="list-group">
      {% for mailing in mailings %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <a href="{% url 'main:mailing_detail' mailing.pk %}">
            {{ mailing.time_to_send }} - {{ mailing.end_time }}
          </a>
          <div class="btn-group">
            <a class="btn btn-danger" href="{% url 'main:delete' mailing.pk %}">Удалить</a>
            <a class="btn btn-primary" href="{% url 'main:update' mailing.pk %}">Редактировать</a>
          </div>
        </div>
      </li>
      {% empty %}
      <li class="list-group-item">Пока нет ни одной записи.</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

main/templates/main/report.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container mt-5">
  <h1 class="text-center">Отчет о доставке рассылок</h1>
  <div class="row justify-content-center">
    <div class="col-md-12">
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Дата и время</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ сервера</th>
          </tr>
        </thead>
        <tbody>
          {% for log in logs %}
            <tr>
              <td>{{ log.attempt_time }}</td>
              <td>{{ log.status }}</td>
              <td>{{ log.response }}</td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="3" class="text-center">Нет данных о доставке</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/update_mailing.html
{% extends 'main/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-12">
                <h2>Детали рассылки</h2>
                <p>Номер рассылки: {{ mailing.id }}</p>
                <p>Вермя старта: {{ mailing.time_to_send }}</p>
                <p>Время конца: {{ mailing.end_time }}</p>
                {% for message in messages %}
                <p>Message ID: {{ message.id }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}